### ISSUE TITLE
how to get file list

### ISSUE THREAD

**Issue by colonist115** [kiewic/FtpClient#4]
Hello! :) I'm student in Republic of Korea. First, My English may hinder your understanding.
 I saw the FTP Client in your github. I use Unity-UWP.  The ftp client sample project works very well. I'd like to add the ability to import a Ftp file list. What should I do? Please reply :)

**Comment by kiewic** [comment]
Hi, 

it has been a long time since the last time I touched that project. But if you know the FTP command you need, you will need to execute it somehow like this:

        internal Task<FtpResponse> SizeAsync(string fileName)
        {
            string command = string.Format("SIZE {0}\r\n", fileName);
            return SendCommandAndGetResponseAsync(command);
        }

Replacing `SIZE {0}` with your command.

**Comment by colonist115** [comment]
Thank reply 👍 

First, I solved the problem.
I used FTP Command 'LIST'. 
After and I read the data in the buffer as your DownloadAsync did.
After turning the byte array into a string, I could read it normally.
It was a good chance to study FTP.
Thank you for leaving me a good project.

May your happiness be full.  :) 👍
